version: "2.1"
services:
  leanote:
    image: nykma/leanote:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./conf/app.conf:/go/src/github.com/leanote/leanote/conf/app.conf"
      - './data/leanote/log:/var/log'
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: nykma/leanote-mongodb:latest
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    entrypoint: "/bin/bash"
    command:
      - "/root/start-db.sh"
    healthcheck:
      test: "echo 'db.stats().ok' | mongo 127.0.0.1:27017/leanote --quiet"
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: leanote
    volumes:
      - "./data/mongodb:/data/db"
    ports:
      - "27017:27017"
